### PR TITLE
#1 make creation scripts idempotent

### PR DESCRIPTION
**Pull request by BrentOzar**
For individual proc and table creation scripts.

### CODE REVIEW

**Comment by BrentOzar** [comment]
My first pull request! (After deleting a few, heh.)

To see what changed, click on the "Files changed" tab at the top of this screen. The left side shows the files as they used to be, and the right side shows the new lines I added to those files. If it looks okay, click the Back button in your browser, and then when you're back on this page, click the "Merge pull request" button.

Anytime someone sends you a pull request, make sure it says "Merging can be performed automatically" - if it doesn't say that, then you should leave them a comment asking them to update their branch. It usually means they worked on their own branch for too long of a time, and you made changes since. They can sync on their side pretty easily, but it's not fair to ask you to do that work (because it can be pretty painful to fix conflicts on the maintainer's side.)

**Comment by IanYates** [comment]
Strange...  Github is treating all 5 changed files as binary so won't show diffs.  Is that happening for anyone else here?   (yes I have a dark theme.  no that isn't the cause {hoping there's going to be no egg on my face!})
capture

**Comment by BrentOzar** [comment]
Yeah, it's due to this: https://stackoverflow.com/questions/28145687/why-does-git-think-my-sql-file-is-a-binary-file

**Comment by dsolodow** [comment]
What would be the drawbacks to converting the scripts to UTF8? That would solve the diff issues and shouldn't have any impact on executing the scripts from SSMS.

**Comment by BrentOzar** [comment]
Yeah, totally agreed - that's how we handle our own stuff, too. You wanna do a PR for that?

**Comment by dsolodow** [comment]
Created. :) PR #7

**Comment by BrentOzar** [comment]
@dsolodow thanks sir! If he accepts that one, I'll close this and redo it.

**Comment by BrentOzar** [comment]
Closing this pull request because I need to redo the code with the new UTF8 encoding.

**Pull request closed without merging**
