### PR TITLE
Convert formatting

### PR DESCRIPTION
**Pull request by dsolodow**
Switch scripts from UTF-16 LE to UTF-8. This allows Git to diff them properly

### CODE REVIEW

**Comment by BrentOzar** [comment]
@olahallengren - by default, SSMS saves files in an unusual encoding. Right now, if you click on the "Files changed" tab at the top of this page, you just see a list of "binary" files - even though SQL files are really just text files. There's more information here:

https://stackoverflow.com/questions/28145687/why-does-git-think-my-sql-file-is-a-binary-file

What @dsolodow did was save the files as a different file encoding. After this, you'll be able to see the line-by-line differences in every pull request. For example, here's how one looks for one of our scripts in the First Responder Kit:

online-diff

The original file would be on the left (yours), and the one on the right is the changed lines in the new proposal. Github automatically shows you the newly added (or removed) lines, so you can see at a glance that things are cool.

To accept his changes, hit the merge button here BEFORE you accept anyone else's changes. I know that's scary, heh - but from here on out, it'll be way easier since you'll be able to see changes line by line. (The other existing pull requests from other people - me included - will need to be redone because this is a big change, but that's totally okay, we'll happily do that.)

**Comment by BrentOzar** [comment]
Here's an even better example - I made a few changes to @dsolodow's code, and here's what the built-in Github difference tool shows. His code (yours) is on the left, my changes are on the right. Shows line numbers and exactly what changed.

If you want a walkthrough of how to do this stuff, holler and we can meet today or this weekend if you want.

databasebackup_diff

**Comment by BrentOzar** [comment]
Ola - you can close this pull request since it's replaced by your changes to SSMS settings. Thanks sir!

**Comment by olahallengren** [comment]
I have changed the files to UTF-8.

**Pull request closed without merging**
