### PR TITLE
Wrapping all CommandExecute calls in Try-Catch block

### PR DESCRIPTION
**Pull request by SlavaSQL**
The Idea:
In case of any unpredictable error associated with CommandExecute calls the error might be suppressed from rising and be passed only as @ReturnCode. 

Actual proposed changes:

1. Adding new "Raiserror" parameter : 
@Raiserror nvarchar(max) = 'Y'

2. Wrapping 5 (five) CommandExecute calls in Try-Catch block:
					BEGIN TRY
						EXECUTE @CurrentCommandOutputXX = [dbo].[CommandExecute] BLA-BLA-BLA

						SET @Error = @@ERROR
						IF @Error <> 0 SET @CurrentCommandOutputXX = @Error
						IF @CurrentCommandOutputXX <> 0 SET @ReturnCode = @olahallengren CurrentCommandOutputXX
					END TRY 
					BEGIN CATCH
							IF XACT_STATE() <> 0
							BEGIN
								ROLLBACK TRANSACTION
							END
							SET @ErrorMessage = 'ERROR: ' + CAST(ERROR_NUMBER() AS nvarchar) + ', ' + ISNULL(ERROR_MESSAGE(),'')
							IF @Raiserror = 'Y'
								RAISERROR('%s',16,1,@ErrorMessage) WITH NOWAIT
							ELSE 
								RAISERROR('%s',10,1,@ErrorMessage) WITH NOWAIT
							RAISERROR(@EmptyLine,10,1) WITH NOWAIT
							SET @Error = ERROR_NUMBER()
							SET @ReturnCode = @Error
					END CATCH

### CODE REVIEW

**Comment by olahallengren** [comment]
Let's take a step back and do a small test.

First let's try executing a backup command that will fail.
```
BACKUP DATABASE model TO DISK = 'Q:\model.bak'
```

Msg 3201, Level 16, State 1, Line 2
Cannot open backup device 'Q:\model.bak'. Operating system error 3(The system cannot find the path specified.).
Msg 3013, Level 16, State 1, Line 2
BACKUP DATABASE is terminating abnormally.


Now let's try executing the backup command in a TRY - block.
```
DECLARE @ErrorMessage nvarchar(max)

BEGIN TRY
  BACKUP DATABASE model TO DISK = 'Q:\model.bak'
END TRY
BEGIN CATCH
  SET @ErrorMessage = 'ERROR: ' + CAST(ERROR_NUMBER() AS nvarchar) + ', ' + ISNULL(ERROR_MESSAGE(),'')
  RAISERROR('%s',16,1,@ErrorMessage) WITH NOWAIT
END CATCH
```

Msg 50000, Level 16, State 1, Line 19
ERROR: 3013, BACKUP DATABASE is terminating abnormally.

As you see the BACKUP DATABASE command returns two errors, and when you are using TRY CATCH, you can only capture the second error, with the ERROR_NUMBER() and ERROR_MESSAGE() - functions.

**Comment by SlavaSQL** [comment]
Thanks for pointing at that. Never paid attention to it.

You are absolutely right, if we wrap it in TRY-Catch block we loose the very first error, which is the root cause.
Is there any known way to recapture it????

BTW The only workaround I see is to look at the ERRORLOG file.

Will it be OK if I come up here with a script, which will determine if person want to wrap the call into Try-Catch and do it only then?

Thanks again.

**Comment by olahallengren** [comment]
>You are absolutely right, if we wrap it in TRY-Catch block we loose the very first error, which is the root cause.
Is there any known way to recapture it????

There is no way to capture both both errors (or the first error) using the error functions.

It is possible to rethrow the errors using THROW. However that is only available in SQL Server 2012 and later.

I have the parameter ```@Mode``` in CommandExecute to control if TRY CATCH should be used.

>Will it be OK if I come up here with a script, which will determine if person want to wrap the call into Try-Catch and do it only then?

With this parameter, how would the user find the cause of a failed backup?

**Comment by SlavaSQL** [comment]
Will check the @Mode parameter.

All BACKUP errors are automatically getting into ERRORLOG file.
Are there any exceptions from it?

**Comment by SlavaSQL** [comment]
Checked the @Mode parameter.
It looks like it applies only to "CommandExecute" but not for "DatabaseBackup" procedure itself.
Any error in that wrapper will cause Job failure.

**Comment by olahallengren** [comment]
>Checked the @mode parameter.
It looks like it applies only to "CommandExecute" but not for "DatabaseBackup" procedure itself.

That is correct. This is an internal parameter. I added it because I needed to have different error handling for different commands.

>Any error in that wrapper will cause Job failure.

This is correct. I am not planning to change this.

**Comment by olahallengren** [comment]
>All BACKUP errors are automatically getting into ERRORLOG file.
Are there any exceptions from it?

My understanding is that all backup errors are going into the ERRORLOG.

**Comment by SlavaSQL** [comment]
OK. 
If you change your mind in the future you can pass some dirty work to me.
Will be always glad to help you.

Not sure about that branch. Do you close it or delete completely?

Thanks.

**Comment by olahallengren** [comment]
You can just close it.

**Comment by olahallengren** [comment]
You can also delete your branch if you prefer that.

**Pull request closed without merging**
