### PR TITLE
Issue 726 : BackupType - Option to use lower case in URL

### PR DESCRIPTION
**Pull request by mdaniou**
Adding a bit of code to lowercase urls all the time. I hope this will answer this issue

### CODE REVIEW

**Comment by sethmgray** [comment]
I have similar requirement asking for ability to lower() the backup path. In our case we have Always On AGs that have databases that were not properly cased equivalently between restore operations by dbas and having ability to send at least the database name to lower or upper would help to guarantee the file has some consistent convention making its way to case sensitive systems (storage gateways and s3 in AWS in our case).

**Comment by olahallengren** [comment]
Would you like to have a parameter here to make the directory path lower case or upper case?

**Comment by sethmgray** [comment]
> Would you like to have a parameter here to make the directory path lower case or upper case?

In our case it's best that the path and database name has separate params to put each to upper/lower, but the full path (including db name) would at least allow for predictable and repeatable casing

**Comment by olahallengren** [comment]
Another option could be to introduce new lower/upper case tokens in these parameters:
https://ola.hallengren.com/sql-server-backup.html#DirectoryStructure
https://ola.hallengren.com/sql-server-backup.html#FileName

**Comment by sethmgray** [comment]
I assume the addition of two casing versions of each token would be the
most flexible and least/no impact to the procs arguments.

**Comment by olahallengren** [comment]
>I assume the addition of two casing versions of each token would be the most flexible and least/no impact to the procs arguments.

It would be the most flexible, but also quite cumbersome to pass the parameters correctly, especially if you have both standalone databases and databases in availability groups.

The other option would be to introduce two new parameters, `@DirectoryStructureCase` and `@FileNameCase`, where NULL is the default (as today), but you could set them to LOWER and UPPER.

**Comment by olahallengren** [comment]
I have been doing some work on this. Please have a look at https://github.com/olahallengren/sql-server-maintenance-solution/pull/836.

**Comment by olahallengren** [comment]
I have released this now. Here is the documentation:
https://ola.hallengren.com/sql-server-backup.html#DirectoryStructureCase
https://ola.hallengren.com/sql-server-backup.html#FileNameCase

**Pull request closed without merging**
